IF NOT EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'AuthorPaperIdentification')
	CREATE DATABASE AuthorPaperIdentification

USE AuthorPaperIdentification
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Author')
BEGIN
	CREATE TABLE Author
	(
	Id INT PRIMARY KEY CLUSTERED NOT NULL,
	Name NVARCHAR(1024) NOT NULL,
	Affiliation NVARCHAR(1024) NULL
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Conference')
BEGIN
	CREATE TABLE Conference
	(
	Id INT PRIMARY KEY CLUSTERED NOT NULL,
	ShortName NVARCHAR(200) NOT NULL,
	FullName NVARCHAR(max) NOT NULL,
	HomePage NVARCHAR(1024) NULL
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Journal')
BEGIN
	CREATE TABLE Journal
	(
	Id INT PRIMARY KEY CLUSTERED NOT NULL,
	ShortName NVARCHAR(200) NOT NULL,
	FullName NVARCHAR(max) NOT NULL,
	HomePage NVARCHAR(1024) NULL
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'Paper')
BEGIN
	CREATE TABLE Paper
	(
	Id INT PRIMARY KEY CLUSTERED NOT NULL,
	Title NVARCHAR(1024) NOT NULL,
	Year INT NOT NULL,
	ConferenceId INT NULL REFERENCES Conference(Id),
	JournalId INT NULL REFERENCES Journal(Id),
	Keywords NVARCHAR(max) NULL
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'PaperAuthor')
BEGIN
	CREATE TABLE PaperAuthor
	(
	PaperId INT NOT NULL REFERENCES Paper(Id),
	AuthorId INT NOT NULL REFERENCES Author(Id),
	Name NVARCHAR(1024) NULL,
	Affiliation NVARCHAR(1024) NULL,
	PRIMARY KEY(PaperId, AuthorId)
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'ConfirmedPaper')
BEGIN
	CREATE TABLE ConfirmedPaper
	(
	PaperId INT NOT NULL REFERENCES Paper(Id),
	AuthorId INT NOT NULL REFERENCES Author(Id)
	PRIMARY KEY(PaperId, AuthorId)
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'DeletedPaper')
BEGIN
	CREATE TABLE DeletedPaper
	(
	PaperId INT NOT NULL REFERENCES Paper(Id),
	AuthorId INT NOT NULL REFERENCES Author(Id)
	PRIMARY KEY(PaperId, AuthorId)
	);
END

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_SCHEMA = 'dbo' AND  TABLE_NAME = 'ValidatedPaper')
BEGIN
	CREATE TABLE ValidatedPaper
	(
	PaperId INT NOT NULL REFERENCES Paper(Id),
	AuthorId INT NOT NULL REFERENCES Author(Id)
	PRIMARY KEY(PaperId, AuthorId)
	);
END