//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("kdd2013Model", "paper_conference", "conference", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AuthorPaper.Conference), "paper", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.Paper), true)]
[assembly: EdmRelationshipAttribute("kdd2013Model", "paper_journal", "journal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AuthorPaper.Journal), "paper", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.Paper), true)]
[assembly: EdmRelationshipAttribute("kdd2013Model", "paperkeyword_keyword", "keyword", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AuthorPaper.Keyword), "paperkeyword", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.PaperKeyword), true)]
[assembly: EdmRelationshipAttribute("kdd2013Model", "paperkeyword_paper", "paper", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AuthorPaper.Paper), "paperkeyword", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.PaperKeyword), true)]
[assembly: EdmRelationshipAttribute("kdd2013Model", "validpaper_paper", "Paper", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AuthorPaper.Paper), "ValidPaper", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.ValidPaper), true)]

#endregion

namespace AuthorPaper
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuthorPaperEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuthorPaperEntities object using the connection string found in the 'AuthorPaperEntities' section of the application configuration file.
        /// </summary>
        public AuthorPaperEntities() : base("name=AuthorPaperEntities", "AuthorPaperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuthorPaperEntities object.
        /// </summary>
        public AuthorPaperEntities(string connectionString) : base(connectionString, "AuthorPaperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuthorPaperEntities object.
        /// </summary>
        public AuthorPaperEntities(EntityConnection connection) : base(connection, "AuthorPaperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Author> Authors
        {
            get
            {
                if ((_Authors == null))
                {
                    _Authors = base.CreateObjectSet<Author>("Authors");
                }
                return _Authors;
            }
        }
        private ObjectSet<Author> _Authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Conference> Conferences
        {
            get
            {
                if ((_Conferences == null))
                {
                    _Conferences = base.CreateObjectSet<Conference>("Conferences");
                }
                return _Conferences;
            }
        }
        private ObjectSet<Conference> _Conferences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Journal> Journals
        {
            get
            {
                if ((_Journals == null))
                {
                    _Journals = base.CreateObjectSet<Journal>("Journals");
                }
                return _Journals;
            }
        }
        private ObjectSet<Journal> _Journals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Paper> Papers
        {
            get
            {
                if ((_Papers == null))
                {
                    _Papers = base.CreateObjectSet<Paper>("Papers");
                }
                return _Papers;
            }
        }
        private ObjectSet<Paper> _Papers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaperAuthor> PaperAuthors
        {
            get
            {
                if ((_PaperAuthors == null))
                {
                    _PaperAuthors = base.CreateObjectSet<PaperAuthor>("PaperAuthors");
                }
                return _PaperAuthors;
            }
        }
        private ObjectSet<PaperAuthor> _PaperAuthors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TrainConfirmed> TrainConfirmed
        {
            get
            {
                if ((_TrainConfirmed == null))
                {
                    _TrainConfirmed = base.CreateObjectSet<TrainConfirmed>("TrainConfirmed");
                }
                return _TrainConfirmed;
            }
        }
        private ObjectSet<TrainConfirmed> _TrainConfirmed;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TrainDeleted> TrainDeleted
        {
            get
            {
                if ((_TrainDeleted == null))
                {
                    _TrainDeleted = base.CreateObjectSet<TrainDeleted>("TrainDeleted");
                }
                return _TrainDeleted;
            }
        }
        private ObjectSet<TrainDeleted> _TrainDeleted;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ValidPaper> ValidPapers
        {
            get
            {
                if ((_ValidPapers == null))
                {
                    _ValidPapers = base.CreateObjectSet<ValidPaper>("ValidPapers");
                }
                return _ValidPapers;
            }
        }
        private ObjectSet<ValidPaper> _ValidPapers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Keyword> Keywords
        {
            get
            {
                if ((_Keywords == null))
                {
                    _Keywords = base.CreateObjectSet<Keyword>("Keywords");
                }
                return _Keywords;
            }
        }
        private ObjectSet<Keyword> _Keywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PaperKeyword> PaperKeywords
        {
            get
            {
                if ((_PaperKeywords == null))
                {
                    _PaperKeywords = base.CreateObjectSet<PaperKeyword>("PaperKeywords");
                }
                return _PaperKeywords;
            }
        }
        private ObjectSet<PaperKeyword> _PaperKeywords;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAuthors(Author author)
        {
            base.AddObject("Authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Conferences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConferences(Conference conference)
        {
            base.AddObject("Conferences", conference);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Journals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJournals(Journal journal)
        {
            base.AddObject("Journals", journal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Papers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPapers(Paper paper)
        {
            base.AddObject("Papers", paper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaperAuthors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaperAuthors(PaperAuthor paperAuthor)
        {
            base.AddObject("PaperAuthors", paperAuthor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TrainConfirmed EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrainConfirmed(TrainConfirmed trainConfirmed)
        {
            base.AddObject("TrainConfirmed", trainConfirmed);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TrainDeleted EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTrainDeleted(TrainDeleted trainDeleted)
        {
            base.AddObject("TrainDeleted", trainDeleted);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ValidPapers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToValidPapers(ValidPaper validPaper)
        {
            base.AddObject("ValidPapers", validPaper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Keywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKeywords(Keyword keyword)
        {
            base.AddObject("Keywords", keyword);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PaperKeywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPaperKeywords(PaperKeyword paperKeyword)
        {
            base.AddObject("PaperKeywords", paperKeyword);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="Author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Author object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Author CreateAuthor(global::System.Int64 id)
        {
            Author author = new Author();
            author.Id = id;
            return author;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Affiliation
        {
            get
            {
                return _Affiliation;
            }
            set
            {
                OnAffiliationChanging(value);
                ReportPropertyChanging("Affiliation");
                _Affiliation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Affiliation");
                OnAffiliationChanged();
            }
        }
        private global::System.String _Affiliation;
        partial void OnAffiliationChanging(global::System.String value);
        partial void OnAffiliationChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="Conference")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Conference : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Conference object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Conference CreateConference(global::System.Int64 id)
        {
            Conference conference = new Conference();
            conference.Id = id;
            return conference;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortName
        {
            get
            {
                return _ShortName;
            }
            set
            {
                OnShortNameChanging(value);
                ReportPropertyChanging("ShortName");
                _ShortName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortName");
                OnShortNameChanged();
            }
        }
        private global::System.String _ShortName;
        partial void OnShortNameChanging(global::System.String value);
        partial void OnShortNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomePage
        {
            get
            {
                return _HomePage;
            }
            set
            {
                OnHomePageChanging(value);
                ReportPropertyChanging("HomePage");
                _HomePage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomePage");
                OnHomePageChanged();
            }
        }
        private global::System.String _HomePage;
        partial void OnHomePageChanging(global::System.String value);
        partial void OnHomePageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_conference", "paper")]
        public EntityCollection<Paper> Papers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Paper>("kdd2013Model.paper_conference", "paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Paper>("kdd2013Model.paper_conference", "paper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="Journal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Journal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Journal object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Journal CreateJournal(global::System.Int64 id)
        {
            Journal journal = new Journal();
            journal.Id = id;
            return journal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ShortName
        {
            get
            {
                return _ShortName;
            }
            set
            {
                OnShortNameChanging(value);
                ReportPropertyChanging("ShortName");
                _ShortName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ShortName");
                OnShortNameChanged();
            }
        }
        private global::System.String _ShortName;
        partial void OnShortNameChanging(global::System.String value);
        partial void OnShortNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullName
        {
            get
            {
                return _FullName;
            }
            set
            {
                OnFullNameChanging(value);
                ReportPropertyChanging("FullName");
                _FullName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullName");
                OnFullNameChanged();
            }
        }
        private global::System.String _FullName;
        partial void OnFullNameChanging(global::System.String value);
        partial void OnFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomePage
        {
            get
            {
                return _HomePage;
            }
            set
            {
                OnHomePageChanging(value);
                ReportPropertyChanging("HomePage");
                _HomePage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomePage");
                OnHomePageChanged();
            }
        }
        private global::System.String _HomePage;
        partial void OnHomePageChanging(global::System.String value);
        partial void OnHomePageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_journal", "paper")]
        public EntityCollection<Paper> Papers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Paper>("kdd2013Model.paper_journal", "paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Paper>("kdd2013Model.paper_journal", "paper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="Keyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Keyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Keyword object.
        /// </summary>
        /// <param name="keywordId">Initial value of the KeywordId property.</param>
        public static Keyword CreateKeyword(global::System.Int32 keywordId)
        {
            Keyword keyword = new Keyword();
            keyword.KeywordId = keywordId;
            return keyword;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KeywordId
        {
            get
            {
                return _KeywordId;
            }
            set
            {
                if (_KeywordId != value)
                {
                    OnKeywordIdChanging(value);
                    ReportPropertyChanging("KeywordId");
                    _KeywordId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KeywordId");
                    OnKeywordIdChanged();
                }
            }
        }
        private global::System.Int32 _KeywordId;
        partial void OnKeywordIdChanging(global::System.Int32 value);
        partial void OnKeywordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int64> _Count;
        partial void OnCountChanging(Nullable<global::System.Int64> value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NormalizedCount
        {
            get
            {
                return _NormalizedCount;
            }
            set
            {
                OnNormalizedCountChanging(value);
                ReportPropertyChanging("NormalizedCount");
                _NormalizedCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NormalizedCount");
                OnNormalizedCountChanged();
            }
        }
        private Nullable<global::System.Double> _NormalizedCount;
        partial void OnNormalizedCountChanging(Nullable<global::System.Double> value);
        partial void OnNormalizedCountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paperkeyword_keyword", "paperkeyword")]
        public EntityCollection<PaperKeyword> PaperKeywords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PaperKeyword>("kdd2013Model.paperkeyword_keyword", "paperkeyword");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PaperKeyword>("kdd2013Model.paperkeyword_keyword", "paperkeyword", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="Paper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Paper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Paper object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Paper CreatePaper(global::System.Int64 id)
        {
            Paper paper = new Paper();
            paper.Id = id;
            return paper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Year
        {
            get
            {
                return _Year;
            }
            set
            {
                OnYearChanging(value);
                ReportPropertyChanging("Year");
                _Year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Year");
                OnYearChanged();
            }
        }
        private Nullable<global::System.Int64> _Year;
        partial void OnYearChanging(Nullable<global::System.Int64> value);
        partial void OnYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> ConferenceId
        {
            get
            {
                return _ConferenceId;
            }
            set
            {
                OnConferenceIdChanging(value);
                ReportPropertyChanging("ConferenceId");
                _ConferenceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConferenceId");
                OnConferenceIdChanged();
            }
        }
        private Nullable<global::System.Int64> _ConferenceId;
        partial void OnConferenceIdChanging(Nullable<global::System.Int64> value);
        partial void OnConferenceIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> JournalId
        {
            get
            {
                return _JournalId;
            }
            set
            {
                OnJournalIdChanging(value);
                ReportPropertyChanging("JournalId");
                _JournalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JournalId");
                OnJournalIdChanged();
            }
        }
        private Nullable<global::System.Int64> _JournalId;
        partial void OnJournalIdChanging(Nullable<global::System.Int64> value);
        partial void OnJournalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Keyword
        {
            get
            {
                return _Keyword;
            }
            set
            {
                OnKeywordChanging(value);
                ReportPropertyChanging("Keyword");
                _Keyword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Keyword");
                OnKeywordChanged();
            }
        }
        private global::System.String _Keyword;
        partial void OnKeywordChanging(global::System.String value);
        partial void OnKeywordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_conference", "conference")]
        public Conference Conference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conference>("kdd2013Model.paper_conference", "conference").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conference>("kdd2013Model.paper_conference", "conference").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Conference> ConferenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conference>("kdd2013Model.paper_conference", "conference");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Conference>("kdd2013Model.paper_conference", "conference", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_journal", "journal")]
        public Journal Journal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Journal>("kdd2013Model.paper_journal", "journal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Journal>("kdd2013Model.paper_journal", "journal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Journal> JournalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Journal>("kdd2013Model.paper_journal", "journal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Journal>("kdd2013Model.paper_journal", "journal", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paperkeyword_paper", "paperkeyword")]
        public EntityCollection<PaperKeyword> PaperKeywords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PaperKeyword>("kdd2013Model.paperkeyword_paper", "paperkeyword");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PaperKeyword>("kdd2013Model.paperkeyword_paper", "paperkeyword", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "validpaper_paper", "ValidPaper")]
        public EntityCollection<ValidPaper> validpaper
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ValidPaper>("kdd2013Model.validpaper_paper", "ValidPaper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ValidPaper>("kdd2013Model.validpaper_paper", "ValidPaper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="PaperAuthor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaperAuthor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaperAuthor object.
        /// </summary>
        /// <param name="paperAuthorId">Initial value of the PaperAuthorId property.</param>
        public static PaperAuthor CreatePaperAuthor(global::System.Int32 paperAuthorId)
        {
            PaperAuthor paperAuthor = new PaperAuthor();
            paperAuthor.PaperAuthorId = paperAuthorId;
            return paperAuthor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PaperId
        {
            get
            {
                return _PaperId;
            }
            set
            {
                OnPaperIdChanging(value);
                ReportPropertyChanging("PaperId");
                _PaperId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaperId");
                OnPaperIdChanged();
            }
        }
        private Nullable<global::System.Int64> _PaperId;
        partial void OnPaperIdChanging(Nullable<global::System.Int64> value);
        partial void OnPaperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                OnAuthorIdChanging(value);
                ReportPropertyChanging("AuthorId");
                _AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorId");
                OnAuthorIdChanged();
            }
        }
        private Nullable<global::System.Int64> _AuthorId;
        partial void OnAuthorIdChanging(Nullable<global::System.Int64> value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Affiliation
        {
            get
            {
                return _Affiliation;
            }
            set
            {
                OnAffiliationChanging(value);
                ReportPropertyChanging("Affiliation");
                _Affiliation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Affiliation");
                OnAffiliationChanged();
            }
        }
        private global::System.String _Affiliation;
        partial void OnAffiliationChanging(global::System.String value);
        partial void OnAffiliationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaperAuthorId
        {
            get
            {
                return _PaperAuthorId;
            }
            set
            {
                if (_PaperAuthorId != value)
                {
                    OnPaperAuthorIdChanging(value);
                    ReportPropertyChanging("PaperAuthorId");
                    _PaperAuthorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaperAuthorId");
                    OnPaperAuthorIdChanged();
                }
            }
        }
        private global::System.Int32 _PaperAuthorId;
        partial void OnPaperAuthorIdChanging(global::System.Int32 value);
        partial void OnPaperAuthorIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="PaperKeyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PaperKeyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PaperKeyword object.
        /// </summary>
        /// <param name="paperId">Initial value of the PaperId property.</param>
        /// <param name="keywordId">Initial value of the KeywordId property.</param>
        /// <param name="paperKeywordId">Initial value of the PaperKeywordId property.</param>
        public static PaperKeyword CreatePaperKeyword(global::System.Int64 paperId, global::System.Int32 keywordId, global::System.Int32 paperKeywordId)
        {
            PaperKeyword paperKeyword = new PaperKeyword();
            paperKeyword.PaperId = paperId;
            paperKeyword.KeywordId = keywordId;
            paperKeyword.PaperKeywordId = paperKeywordId;
            return paperKeyword;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 PaperId
        {
            get
            {
                return _PaperId;
            }
            set
            {
                OnPaperIdChanging(value);
                ReportPropertyChanging("PaperId");
                _PaperId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaperId");
                OnPaperIdChanged();
            }
        }
        private global::System.Int64 _PaperId;
        partial void OnPaperIdChanging(global::System.Int64 value);
        partial void OnPaperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> Count
        {
            get
            {
                return _Count;
            }
            set
            {
                OnCountChanging(value);
                ReportPropertyChanging("Count");
                _Count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Count");
                OnCountChanged();
            }
        }
        private Nullable<global::System.Int64> _Count;
        partial void OnCountChanging(Nullable<global::System.Int64> value);
        partial void OnCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NormalizedCount
        {
            get
            {
                return _NormalizedCount;
            }
            set
            {
                OnNormalizedCountChanging(value);
                ReportPropertyChanging("NormalizedCount");
                _NormalizedCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NormalizedCount");
                OnNormalizedCountChanged();
            }
        }
        private Nullable<global::System.Double> _NormalizedCount;
        partial void OnNormalizedCountChanging(Nullable<global::System.Double> value);
        partial void OnNormalizedCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KeywordId
        {
            get
            {
                return _KeywordId;
            }
            set
            {
                OnKeywordIdChanging(value);
                ReportPropertyChanging("KeywordId");
                _KeywordId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KeywordId");
                OnKeywordIdChanged();
            }
        }
        private global::System.Int32 _KeywordId;
        partial void OnKeywordIdChanging(global::System.Int32 value);
        partial void OnKeywordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PaperKeywordId
        {
            get
            {
                return _PaperKeywordId;
            }
            set
            {
                if (_PaperKeywordId != value)
                {
                    OnPaperKeywordIdChanging(value);
                    ReportPropertyChanging("PaperKeywordId");
                    _PaperKeywordId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PaperKeywordId");
                    OnPaperKeywordIdChanged();
                }
            }
        }
        private global::System.Int32 _PaperKeywordId;
        partial void OnPaperKeywordIdChanging(global::System.Int32 value);
        partial void OnPaperKeywordIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> MaxCount
        {
            get
            {
                return _MaxCount;
            }
            set
            {
                OnMaxCountChanging(value);
                ReportPropertyChanging("MaxCount");
                _MaxCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxCount");
                OnMaxCountChanged();
            }
        }
        private Nullable<global::System.Int64> _MaxCount;
        partial void OnMaxCountChanging(Nullable<global::System.Int64> value);
        partial void OnMaxCountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paperkeyword_keyword", "keyword")]
        public Keyword Keyword
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Keyword>("kdd2013Model.paperkeyword_keyword", "keyword").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Keyword>("kdd2013Model.paperkeyword_keyword", "keyword").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Keyword> KeywordReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Keyword>("kdd2013Model.paperkeyword_keyword", "keyword");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Keyword>("kdd2013Model.paperkeyword_keyword", "keyword", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paperkeyword_paper", "paper")]
        public Paper Paper
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paper>("kdd2013Model.paperkeyword_paper", "paper").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paper>("kdd2013Model.paperkeyword_paper", "paper").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Paper> PaperReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paper>("kdd2013Model.paperkeyword_paper", "paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Paper>("kdd2013Model.paperkeyword_paper", "paper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="TrainConfirmed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TrainConfirmed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TrainConfirmed object.
        /// </summary>
        /// <param name="trainConfirmedId">Initial value of the TrainConfirmedId property.</param>
        public static TrainConfirmed CreateTrainConfirmed(global::System.Int32 trainConfirmedId)
        {
            TrainConfirmed trainConfirmed = new TrainConfirmed();
            trainConfirmed.TrainConfirmedId = trainConfirmedId;
            return trainConfirmed;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                OnAuthorIdChanging(value);
                ReportPropertyChanging("AuthorId");
                _AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorId");
                OnAuthorIdChanged();
            }
        }
        private Nullable<global::System.Int64> _AuthorId;
        partial void OnAuthorIdChanging(Nullable<global::System.Int64> value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PaperId
        {
            get
            {
                return _PaperId;
            }
            set
            {
                OnPaperIdChanging(value);
                ReportPropertyChanging("PaperId");
                _PaperId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaperId");
                OnPaperIdChanged();
            }
        }
        private Nullable<global::System.Int64> _PaperId;
        partial void OnPaperIdChanging(Nullable<global::System.Int64> value);
        partial void OnPaperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TrainConfirmedId
        {
            get
            {
                return _TrainConfirmedId;
            }
            set
            {
                if (_TrainConfirmedId != value)
                {
                    OnTrainConfirmedIdChanging(value);
                    ReportPropertyChanging("TrainConfirmedId");
                    _TrainConfirmedId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainConfirmedId");
                    OnTrainConfirmedIdChanged();
                }
            }
        }
        private global::System.Int32 _TrainConfirmedId;
        partial void OnTrainConfirmedIdChanging(global::System.Int32 value);
        partial void OnTrainConfirmedIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="TrainDeleted")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TrainDeleted : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TrainDeleted object.
        /// </summary>
        /// <param name="trainDeletedId">Initial value of the TrainDeletedId property.</param>
        public static TrainDeleted CreateTrainDeleted(global::System.Int32 trainDeletedId)
        {
            TrainDeleted trainDeleted = new TrainDeleted();
            trainDeleted.TrainDeletedId = trainDeletedId;
            return trainDeleted;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                OnAuthorIdChanging(value);
                ReportPropertyChanging("AuthorId");
                _AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorId");
                OnAuthorIdChanged();
            }
        }
        private Nullable<global::System.Int64> _AuthorId;
        partial void OnAuthorIdChanging(Nullable<global::System.Int64> value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PaperId
        {
            get
            {
                return _PaperId;
            }
            set
            {
                OnPaperIdChanging(value);
                ReportPropertyChanging("PaperId");
                _PaperId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaperId");
                OnPaperIdChanged();
            }
        }
        private Nullable<global::System.Int64> _PaperId;
        partial void OnPaperIdChanging(Nullable<global::System.Int64> value);
        partial void OnPaperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TrainDeletedId
        {
            get
            {
                return _TrainDeletedId;
            }
            set
            {
                if (_TrainDeletedId != value)
                {
                    OnTrainDeletedIdChanging(value);
                    ReportPropertyChanging("TrainDeletedId");
                    _TrainDeletedId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TrainDeletedId");
                    OnTrainDeletedIdChanged();
                }
            }
        }
        private global::System.Int32 _TrainDeletedId;
        partial void OnTrainDeletedIdChanging(global::System.Int32 value);
        partial void OnTrainDeletedIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="ValidPaper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ValidPaper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ValidPaper object.
        /// </summary>
        /// <param name="validPaperId">Initial value of the ValidPaperId property.</param>
        public static ValidPaper CreateValidPaper(global::System.Int32 validPaperId)
        {
            ValidPaper validPaper = new ValidPaper();
            validPaper.ValidPaperId = validPaperId;
            return validPaper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> AuthorId
        {
            get
            {
                return _AuthorId;
            }
            set
            {
                OnAuthorIdChanging(value);
                ReportPropertyChanging("AuthorId");
                _AuthorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthorId");
                OnAuthorIdChanged();
            }
        }
        private Nullable<global::System.Int64> _AuthorId;
        partial void OnAuthorIdChanging(Nullable<global::System.Int64> value);
        partial void OnAuthorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> PaperId
        {
            get
            {
                return _PaperId;
            }
            set
            {
                OnPaperIdChanging(value);
                ReportPropertyChanging("PaperId");
                _PaperId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PaperId");
                OnPaperIdChanged();
            }
        }
        private Nullable<global::System.Int64> _PaperId;
        partial void OnPaperIdChanging(Nullable<global::System.Int64> value);
        partial void OnPaperIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ValidPaperId
        {
            get
            {
                return _ValidPaperId;
            }
            set
            {
                if (_ValidPaperId != value)
                {
                    OnValidPaperIdChanging(value);
                    ReportPropertyChanging("ValidPaperId");
                    _ValidPaperId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ValidPaperId");
                    OnValidPaperIdChanged();
                }
            }
        }
        private global::System.Int32 _ValidPaperId;
        partial void OnValidPaperIdChanging(global::System.Int32 value);
        partial void OnValidPaperIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "validpaper_paper", "Paper")]
        public Paper paper
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paper>("kdd2013Model.validpaper_paper", "Paper").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paper>("kdd2013Model.validpaper_paper", "Paper").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Paper> paperReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Paper>("kdd2013Model.validpaper_paper", "Paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Paper>("kdd2013Model.validpaper_paper", "Paper", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
