//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("kdd2013Model", "paperkeyword", "keyword", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.keyword), "paper", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.paper))]
[assembly: EdmRelationshipAttribute("kdd2013Model", "paper_conference", "conference", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AuthorPaper.conference), "paper", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.paper), true)]
[assembly: EdmRelationshipAttribute("kdd2013Model", "paper_journal", "journal", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AuthorPaper.journal), "paper", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AuthorPaper.paper), true)]

#endregion

namespace AuthorPaper
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AuthorPaperEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AuthorPaperEntities object using the connection string found in the 'AuthorPaperEntities' section of the application configuration file.
        /// </summary>
        public AuthorPaperEntities() : base("name=AuthorPaperEntities", "AuthorPaperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuthorPaperEntities object.
        /// </summary>
        public AuthorPaperEntities(string connectionString) : base(connectionString, "AuthorPaperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AuthorPaperEntities object.
        /// </summary>
        public AuthorPaperEntities(EntityConnection connection) : base(connection, "AuthorPaperEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<author> authors
        {
            get
            {
                if ((_authors == null))
                {
                    _authors = base.CreateObjectSet<author>("authors");
                }
                return _authors;
            }
        }
        private ObjectSet<author> _authors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<conference> conferences
        {
            get
            {
                if ((_conferences == null))
                {
                    _conferences = base.CreateObjectSet<conference>("conferences");
                }
                return _conferences;
            }
        }
        private ObjectSet<conference> _conferences;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<journal> journals
        {
            get
            {
                if ((_journals == null))
                {
                    _journals = base.CreateObjectSet<journal>("journals");
                }
                return _journals;
            }
        }
        private ObjectSet<journal> _journals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<paper> papers
        {
            get
            {
                if ((_papers == null))
                {
                    _papers = base.CreateObjectSet<paper>("papers");
                }
                return _papers;
            }
        }
        private ObjectSet<paper> _papers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<paperauthor> paperauthor
        {
            get
            {
                if ((_paperauthor == null))
                {
                    _paperauthor = base.CreateObjectSet<paperauthor>("paperauthor");
                }
                return _paperauthor;
            }
        }
        private ObjectSet<paperauthor> _paperauthor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<trainconfirmed> trainconfirmed
        {
            get
            {
                if ((_trainconfirmed == null))
                {
                    _trainconfirmed = base.CreateObjectSet<trainconfirmed>("trainconfirmed");
                }
                return _trainconfirmed;
            }
        }
        private ObjectSet<trainconfirmed> _trainconfirmed;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<traindeleted> traindeleted
        {
            get
            {
                if ((_traindeleted == null))
                {
                    _traindeleted = base.CreateObjectSet<traindeleted>("traindeleted");
                }
                return _traindeleted;
            }
        }
        private ObjectSet<traindeleted> _traindeleted;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<validpaper> validpaper
        {
            get
            {
                if ((_validpaper == null))
                {
                    _validpaper = base.CreateObjectSet<validpaper>("validpaper");
                }
                return _validpaper;
            }
        }
        private ObjectSet<validpaper> _validpaper;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<keyword> keyword
        {
            get
            {
                if ((_keyword == null))
                {
                    _keyword = base.CreateObjectSet<keyword>("keyword");
                }
                return _keyword;
            }
        }
        private ObjectSet<keyword> _keyword;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the authors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToauthors(author author)
        {
            base.AddObject("authors", author);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the conferences EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToconferences(conference conference)
        {
            base.AddObject("conferences", conference);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the journals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTojournals(journal journal)
        {
            base.AddObject("journals", journal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the papers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopapers(paper paper)
        {
            base.AddObject("papers", paper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the paperauthor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopaperauthor(paperauthor paperauthor)
        {
            base.AddObject("paperauthor", paperauthor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the trainconfirmed EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotrainconfirmed(trainconfirmed trainconfirmed)
        {
            base.AddObject("trainconfirmed", trainconfirmed);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the traindeleted EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotraindeleted(traindeleted traindeleted)
        {
            base.AddObject("traindeleted", traindeleted);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the validpaper EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTovalidpaper(validpaper validpaper)
        {
            base.AddObject("validpaper", validpaper);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the keyword EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTokeyword(keyword keyword)
        {
            base.AddObject("keyword", keyword);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="author")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class author : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new author object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static author Createauthor(global::System.Int64 id)
        {
            author author = new author();
            author.id = id;
            return author;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String affiliation
        {
            get
            {
                return _affiliation;
            }
            set
            {
                OnaffiliationChanging(value);
                ReportPropertyChanging("affiliation");
                _affiliation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("affiliation");
                OnaffiliationChanged();
            }
        }
        private global::System.String _affiliation;
        partial void OnaffiliationChanging(global::System.String value);
        partial void OnaffiliationChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="conference")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class conference : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new conference object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static conference Createconference(global::System.Int64 id)
        {
            conference conference = new conference();
            conference.id = id;
            return conference;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shortname
        {
            get
            {
                return _shortname;
            }
            set
            {
                OnshortnameChanging(value);
                ReportPropertyChanging("shortname");
                _shortname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shortname");
                OnshortnameChanged();
            }
        }
        private global::System.String _shortname;
        partial void OnshortnameChanging(global::System.String value);
        partial void OnshortnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fullname
        {
            get
            {
                return _fullname;
            }
            set
            {
                OnfullnameChanging(value);
                ReportPropertyChanging("fullname");
                _fullname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fullname");
                OnfullnameChanged();
            }
        }
        private global::System.String _fullname;
        partial void OnfullnameChanging(global::System.String value);
        partial void OnfullnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String homepage
        {
            get
            {
                return _homepage;
            }
            set
            {
                OnhomepageChanging(value);
                ReportPropertyChanging("homepage");
                _homepage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("homepage");
                OnhomepageChanged();
            }
        }
        private global::System.String _homepage;
        partial void OnhomepageChanging(global::System.String value);
        partial void OnhomepageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_conference", "paper")]
        public EntityCollection<paper> paper
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paper>("kdd2013Model.paper_conference", "paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paper>("kdd2013Model.paper_conference", "paper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="journal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class journal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new journal object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static journal Createjournal(global::System.Int64 id)
        {
            journal journal = new journal();
            journal.id = id;
            return journal;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String shortname
        {
            get
            {
                return _shortname;
            }
            set
            {
                OnshortnameChanging(value);
                ReportPropertyChanging("shortname");
                _shortname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("shortname");
                OnshortnameChanged();
            }
        }
        private global::System.String _shortname;
        partial void OnshortnameChanging(global::System.String value);
        partial void OnshortnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String fullname
        {
            get
            {
                return _fullname;
            }
            set
            {
                OnfullnameChanging(value);
                ReportPropertyChanging("fullname");
                _fullname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("fullname");
                OnfullnameChanged();
            }
        }
        private global::System.String _fullname;
        partial void OnfullnameChanging(global::System.String value);
        partial void OnfullnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String homepage
        {
            get
            {
                return _homepage;
            }
            set
            {
                OnhomepageChanging(value);
                ReportPropertyChanging("homepage");
                _homepage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("homepage");
                OnhomepageChanged();
            }
        }
        private global::System.String _homepage;
        partial void OnhomepageChanging(global::System.String value);
        partial void OnhomepageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_journal", "paper")]
        public EntityCollection<paper> paper
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paper>("kdd2013Model.paper_journal", "paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paper>("kdd2013Model.paper_journal", "paper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="keyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class keyword : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new keyword object.
        /// </summary>
        /// <param name="keywordid">Initial value of the keywordid property.</param>
        public static keyword Createkeyword(global::System.Int64 keywordid)
        {
            keyword keyword = new keyword();
            keyword.keywordid = keywordid;
            return keyword;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 keywordid
        {
            get
            {
                return _keywordid;
            }
            set
            {
                if (_keywordid != value)
                {
                    OnkeywordidChanging(value);
                    ReportPropertyChanging("keywordid");
                    _keywordid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("keywordid");
                    OnkeywordidChanged();
                }
            }
        }
        private global::System.Int64 _keywordid;
        partial void OnkeywordidChanging(global::System.Int64 value);
        partial void OnkeywordidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> count
        {
            get
            {
                return _count;
            }
            set
            {
                OncountChanging(value);
                ReportPropertyChanging("count");
                _count = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("count");
                OncountChanged();
            }
        }
        private Nullable<global::System.Int64> _count;
        partial void OncountChanging(Nullable<global::System.Int64> value);
        partial void OncountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.String _value;
        partial void OnvalueChanging(global::System.String value);
        partial void OnvalueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> normalizedcount
        {
            get
            {
                return _normalizedcount;
            }
            set
            {
                OnnormalizedcountChanging(value);
                ReportPropertyChanging("normalizedcount");
                _normalizedcount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("normalizedcount");
                OnnormalizedcountChanged();
            }
        }
        private Nullable<global::System.Double> _normalizedcount;
        partial void OnnormalizedcountChanging(Nullable<global::System.Double> value);
        partial void OnnormalizedcountChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paperkeyword", "paper")]
        public EntityCollection<paper> papers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<paper>("kdd2013Model.paperkeyword", "paper");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<paper>("kdd2013Model.paperkeyword", "paper", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="paper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new paper object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static paper Createpaper(global::System.Int64 id)
        {
            paper paper = new paper();
            paper.id = id;
            return paper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private Nullable<global::System.Int64> _year;
        partial void OnyearChanging(Nullable<global::System.Int64> value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> conferenceid
        {
            get
            {
                return _conferenceid;
            }
            set
            {
                OnconferenceidChanging(value);
                ReportPropertyChanging("conferenceid");
                _conferenceid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("conferenceid");
                OnconferenceidChanged();
            }
        }
        private Nullable<global::System.Int64> _conferenceid;
        partial void OnconferenceidChanging(Nullable<global::System.Int64> value);
        partial void OnconferenceidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> journalid
        {
            get
            {
                return _journalid;
            }
            set
            {
                OnjournalidChanging(value);
                ReportPropertyChanging("journalid");
                _journalid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("journalid");
                OnjournalidChanged();
            }
        }
        private Nullable<global::System.Int64> _journalid;
        partial void OnjournalidChanging(Nullable<global::System.Int64> value);
        partial void OnjournalidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String keyword
        {
            get
            {
                return _keyword;
            }
            set
            {
                OnkeywordChanging(value);
                ReportPropertyChanging("keyword");
                _keyword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("keyword");
                OnkeywordChanged();
            }
        }
        private global::System.String _keyword;
        partial void OnkeywordChanging(global::System.String value);
        partial void OnkeywordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paperkeyword", "keyword")]
        public EntityCollection<keyword> keywords
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<keyword>("kdd2013Model.paperkeyword", "keyword");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<keyword>("kdd2013Model.paperkeyword", "keyword", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_conference", "conference")]
        public conference conference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conference>("kdd2013Model.paper_conference", "conference").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conference>("kdd2013Model.paper_conference", "conference").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<conference> conferenceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<conference>("kdd2013Model.paper_conference", "conference");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<conference>("kdd2013Model.paper_conference", "conference", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("kdd2013Model", "paper_journal", "journal")]
        public journal journal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<journal>("kdd2013Model.paper_journal", "journal").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<journal>("kdd2013Model.paper_journal", "journal").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<journal> journalReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<journal>("kdd2013Model.paper_journal", "journal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<journal>("kdd2013Model.paper_journal", "journal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="paperauthor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class paperauthor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new paperauthor object.
        /// </summary>
        /// <param name="paperauthorid">Initial value of the paperauthorid property.</param>
        public static paperauthor Createpaperauthor(global::System.Int32 paperauthorid)
        {
            paperauthor paperauthor = new paperauthor();
            paperauthor.paperauthorid = paperauthorid;
            return paperauthor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> paperid
        {
            get
            {
                return _paperid;
            }
            set
            {
                OnpaperidChanging(value);
                ReportPropertyChanging("paperid");
                _paperid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paperid");
                OnpaperidChanged();
            }
        }
        private Nullable<global::System.Int64> _paperid;
        partial void OnpaperidChanging(Nullable<global::System.Int64> value);
        partial void OnpaperidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> authorid
        {
            get
            {
                return _authorid;
            }
            set
            {
                OnauthoridChanging(value);
                ReportPropertyChanging("authorid");
                _authorid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("authorid");
                OnauthoridChanged();
            }
        }
        private Nullable<global::System.Int64> _authorid;
        partial void OnauthoridChanging(Nullable<global::System.Int64> value);
        partial void OnauthoridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String affiliation
        {
            get
            {
                return _affiliation;
            }
            set
            {
                OnaffiliationChanging(value);
                ReportPropertyChanging("affiliation");
                _affiliation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("affiliation");
                OnaffiliationChanged();
            }
        }
        private global::System.String _affiliation;
        partial void OnaffiliationChanging(global::System.String value);
        partial void OnaffiliationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 paperauthorid
        {
            get
            {
                return _paperauthorid;
            }
            set
            {
                if (_paperauthorid != value)
                {
                    OnpaperauthoridChanging(value);
                    ReportPropertyChanging("paperauthorid");
                    _paperauthorid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("paperauthorid");
                    OnpaperauthoridChanged();
                }
            }
        }
        private global::System.Int32 _paperauthorid;
        partial void OnpaperauthoridChanging(global::System.Int32 value);
        partial void OnpaperauthoridChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="trainconfirmed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class trainconfirmed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new trainconfirmed object.
        /// </summary>
        /// <param name="trainconfirmedid">Initial value of the trainconfirmedid property.</param>
        public static trainconfirmed Createtrainconfirmed(global::System.Int32 trainconfirmedid)
        {
            trainconfirmed trainconfirmed = new trainconfirmed();
            trainconfirmed.trainconfirmedid = trainconfirmedid;
            return trainconfirmed;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> authorid
        {
            get
            {
                return _authorid;
            }
            set
            {
                OnauthoridChanging(value);
                ReportPropertyChanging("authorid");
                _authorid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("authorid");
                OnauthoridChanged();
            }
        }
        private Nullable<global::System.Int64> _authorid;
        partial void OnauthoridChanging(Nullable<global::System.Int64> value);
        partial void OnauthoridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> paperid
        {
            get
            {
                return _paperid;
            }
            set
            {
                OnpaperidChanging(value);
                ReportPropertyChanging("paperid");
                _paperid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paperid");
                OnpaperidChanged();
            }
        }
        private Nullable<global::System.Int64> _paperid;
        partial void OnpaperidChanging(Nullable<global::System.Int64> value);
        partial void OnpaperidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 trainconfirmedid
        {
            get
            {
                return _trainconfirmedid;
            }
            set
            {
                if (_trainconfirmedid != value)
                {
                    OntrainconfirmedidChanging(value);
                    ReportPropertyChanging("trainconfirmedid");
                    _trainconfirmedid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("trainconfirmedid");
                    OntrainconfirmedidChanged();
                }
            }
        }
        private global::System.Int32 _trainconfirmedid;
        partial void OntrainconfirmedidChanging(global::System.Int32 value);
        partial void OntrainconfirmedidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="traindeleted")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class traindeleted : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new traindeleted object.
        /// </summary>
        /// <param name="traindeletedid">Initial value of the traindeletedid property.</param>
        public static traindeleted Createtraindeleted(global::System.Int32 traindeletedid)
        {
            traindeleted traindeleted = new traindeleted();
            traindeleted.traindeletedid = traindeletedid;
            return traindeleted;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> authorid
        {
            get
            {
                return _authorid;
            }
            set
            {
                OnauthoridChanging(value);
                ReportPropertyChanging("authorid");
                _authorid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("authorid");
                OnauthoridChanged();
            }
        }
        private Nullable<global::System.Int64> _authorid;
        partial void OnauthoridChanging(Nullable<global::System.Int64> value);
        partial void OnauthoridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> paperid
        {
            get
            {
                return _paperid;
            }
            set
            {
                OnpaperidChanging(value);
                ReportPropertyChanging("paperid");
                _paperid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paperid");
                OnpaperidChanged();
            }
        }
        private Nullable<global::System.Int64> _paperid;
        partial void OnpaperidChanging(Nullable<global::System.Int64> value);
        partial void OnpaperidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 traindeletedid
        {
            get
            {
                return _traindeletedid;
            }
            set
            {
                if (_traindeletedid != value)
                {
                    OntraindeletedidChanging(value);
                    ReportPropertyChanging("traindeletedid");
                    _traindeletedid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("traindeletedid");
                    OntraindeletedidChanged();
                }
            }
        }
        private global::System.Int32 _traindeletedid;
        partial void OntraindeletedidChanging(global::System.Int32 value);
        partial void OntraindeletedidChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="kdd2013Model", Name="validpaper")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class validpaper : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new validpaper object.
        /// </summary>
        /// <param name="validpaperid">Initial value of the validpaperid property.</param>
        public static validpaper Createvalidpaper(global::System.Int32 validpaperid)
        {
            validpaper validpaper = new validpaper();
            validpaper.validpaperid = validpaperid;
            return validpaper;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> authorid
        {
            get
            {
                return _authorid;
            }
            set
            {
                OnauthoridChanging(value);
                ReportPropertyChanging("authorid");
                _authorid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("authorid");
                OnauthoridChanged();
            }
        }
        private Nullable<global::System.Int64> _authorid;
        partial void OnauthoridChanging(Nullable<global::System.Int64> value);
        partial void OnauthoridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> paperid
        {
            get
            {
                return _paperid;
            }
            set
            {
                OnpaperidChanging(value);
                ReportPropertyChanging("paperid");
                _paperid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("paperid");
                OnpaperidChanged();
            }
        }
        private Nullable<global::System.Int64> _paperid;
        partial void OnpaperidChanging(Nullable<global::System.Int64> value);
        partial void OnpaperidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 validpaperid
        {
            get
            {
                return _validpaperid;
            }
            set
            {
                if (_validpaperid != value)
                {
                    OnvalidpaperidChanging(value);
                    ReportPropertyChanging("validpaperid");
                    _validpaperid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("validpaperid");
                    OnvalidpaperidChanged();
                }
            }
        }
        private global::System.Int32 _validpaperid;
        partial void OnvalidpaperidChanging(global::System.Int32 value);
        partial void OnvalidpaperidChanged();

        #endregion

    
    }

    #endregion

    
}
