//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorPaperIdentification
{
    using System;
    using System.Collections.Generic;
    
    public partial class Author
    {
        public Author()
        {
            this.PaperAuthors = new HashSet<PaperAuthor>();
            this.Papers = new HashSet<Paper>();
            this.Papers1 = new HashSet<Paper>();
            this.Papers2 = new HashSet<Paper>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Affiliation { get; set; }
    
        public virtual ICollection<PaperAuthor> PaperAuthors { get; set; }
        public virtual ICollection<Paper> Papers { get; set; }
        public virtual ICollection<Paper> Papers1 { get; set; }
        public virtual ICollection<Paper> Papers2 { get; set; }
    }
}
