//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthorPaperIdentification
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paper
    {
        public Paper()
        {
            this.PaperAuthors = new HashSet<PaperAuthor>();
            this.Authors = new HashSet<Author>();
            this.Authors1 = new HashSet<Author>();
            this.Authors2 = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public int Year { get; set; }
        public Nullable<int> ConferenceId { get; set; }
        public Nullable<int> JournalId { get; set; }
        public string Keywords { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual Journal Journal { get; set; }
        public virtual ICollection<PaperAuthor> PaperAuthors { get; set; }
        public virtual ICollection<Author> Authors { get; set; }
        public virtual ICollection<Author> Authors1 { get; set; }
        public virtual ICollection<Author> Authors2 { get; set; }
    }
}
